control:
  startNum: 0
  endNum: 2000
  mergeNum: 10
  timeOut: 100
  outFile: E:\tool\video\video\out\j%03d.ts
  threadNum: 8
  host: https://zuikzy.603ee.com
  playList: config\playlist.m3u8
  tsPath: /2019/05/13/HOs9ma6rLRaeuM1n/

headers:
  Origin: https://zuikzy.603ee.com
  Referer: http://www.6myy.com/player/ckplayerm3u8.html
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36